### ISSUE TITLE
why P(y=1|c=i, x)=v_i?

### ISSUE THREAD

**Issue by dragen1860** [whyjay/memoryGAN#3]
Hi, author:
  I found it's confused to understand why `P(y=1|c=i, x)` can be defined as `v_i`. In my opinion, the memory related variable (K, v, a, h) is global and have no direct relation with x. So i cant understand why.

**Comment by whyjay** [comment]
We can remove `x` due to Markov property (value is independent to `x` if we have `c`)
`P(y=1|c=i, x) = P(y=1|c=i) = v_i`
Note that once you have vMF component (or memory index) `i`, 
`P(y=1|c=i)` is automatically determined to be the value `v` of i-th memory slot. 

Another possible cause of the confusion is notation `x`. 
You might want to consider `P(c=i|x)` as an arbitrary function that estimates posterior.
In our case, we define the estimator with a inference network mu(x) and some exponential computation `exp(kappa K_i*mu(x)) / sum_j exp(kappa K_j*mu(x)) `
